language: node_js
node_js:
  - "stable"

scripts:
  - yarn install
  - yarn test
  - yarn build
  
deploy:
  provider: surge
  skip_cleanip: true
  domain: spiteful-idea.surge.sh
  project: ./build/

on:
  branch: master  